# Generated by Django 5.0.2 on 2024-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waitingapproval', 'Waiting approval'), ('active', 'Ative'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
