# Generated by Django 5.0.2 on 2024-03-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='service',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp_number',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waitingapproval', 'Waiting approval'), ('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
