# Generated by Django 5.0.2 on 2024-03-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='precise_location',
            field=models.CharField(default='this area', max_length=50),
        ),
    ]
