# Generated by Django 5.0.3 on 2024-04-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_review_user_rating_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
